### ISSUE TITLE
Latest Version Fails To Build

### ISSUE THREAD

**Issue by Kfeavel** [lufinkey/MobileBrawler#11]
Compiles fine until the "Linking" stage, when Xcode fires the following errors:

```
Undefined symbols for architecture armv7:
  "SmashBros::Menu::GroupRulesMenu::GroupRulesMenu(SmashBros::SmashData const&, SmashBros::GroupSmashData const&)", referenced from: SmashBros::Menu::GroupMenu::GroupMenu(SmashBros::SmashData const&) in GroupMenu.o
"SmashBros::Menu::GroupSmashStageSelectMenu::GroupSmashStageSelectMenu(SmashBros::SmashData const&, SmashBros::GroupSmashData const&)", referenced from:
      SmashBros::Menu::GroupSmashCharacterSelectMenu::GroupSmashCharacterSelectMenu(SmashBros::SmashData const&, SmashBros::GroupSmashData const&) in GroupSmashCharacterSelectMenu.o
  "SmashBros::InitialLoadListener::InitialLoadListener(GameLibrary::Window*)", referenced from:
      SmashBros::Game::loadContent(GameLibrary::AssetManager*) in Game.o
ld: symbol(s) not found for architecture armv7
```

**Comment by lufinkey** [comment]
The xcode project needs the new files added to it. I didn't update the xcode project yet

**Comment by lufinkey** [comment]
Could you possibly update the xcode project?

**Comment by Kfeavel** [comment]
Sure. I just need a list of the files and where they are.
- Keeton Feavel

**Comment by lufinkey** [comment]
I believe it is just the InitialLoadListener class in src/SmashBros/Load

**Comment by lufinkey** [comment]
One more on the latest commit. The ActorMenuElement class inside src/GameLibrary/Screen/UI

**Comment by Kfeavel** [comment]
Still fails...

**Comment by lufinkey** [comment]
what is the error?

**Comment by Kfeavel** [comment]
Undefined symbols for architecture armv7:
      "SmashBros::Menu::GroupSmashStageSelectMenu::GroupSmashStageSelectMenu(SmashBros::SmashData const&, SmashBros::GroupSmashData const&)", referenced from:
              SmashBros::Menu::GroupSmashCharacterSelectMenu::GroupSmashCharacterSelectMenu(SmashBros::SmashData const&, SmashBros::GroupSmashData const&) in GroupSmashCharacterSelectMenu.o
  "SmashBros::Menu::GroupRulesMenu::GroupRulesMenu(SmashBros::SmashData const&,     SmashBros::GroupSmashData const&)", referenced from:
      SmashBros::Menu::GroupMenu::GroupMenu(SmashBros::SmashData const&) in GroupMenu.o
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by lufinkey** [comment]
Oh you also need to add the StageSelect classes inside of
src/SmashBros/Menu/Base/StageSelect

**Comment by Kfeavel** [comment]
Same error still. (The files were missing though. Kudos to you for finding them.)

**Comment by lufinkey** [comment]
Make a pull request, and I'll fix it.

**Comment by lufinkey** [comment]
fixed.
