### ISSUE TITLE
Stage Loader Not Functioning Properly

### ISSUE THREAD

**Issue by Kfeavel** [lufinkey/MobileBrawler#13]
After adding a new stage module to the assets/stages folder, MobileBrawler fails to load the corresponding icon and is unclickable. All it shows is a blank, white icon. Is this a bug or did you limit the ammount of stages that can be loaded?
![ios simulator screen shot jan 30 2015 10 10 33 pm](https://cloud.githubusercontent.com/assets/3119047/5986611/d7bf5ecc-a8cc-11e4-8463-470e4e265d3a.png)

**Comment by Kfeavel** [comment]
I'm going to uncomment the minsmash version checker because it aids in logging what stages and/or characters are loaded into memory. I'll recomment it after doing some debugging.

**Comment by lufinkey** [comment]
If you named the icon preview.png, then its not going to work, because it
loads icon.png, because preview and icon are different things

**Comment by Kfeavel** [comment]
Yeah, I have both in the folder.

**Comment by lufinkey** [comment]
Well, I'm too tired right now to deal with that. I'll check it out when I
get the chance

**Comment by Kfeavel** [comment]
Yeah, it isn't anything major. It can be fixed after the rest of the menu stuff is completed. I'm going to push to my repo in a bit.
