### ISSUE TITLE
CharacterSelect_PlayerPanel.cpp Bad Access

### ISSUE THREAD

**Issue by Kfeavel** [lufinkey/MobileBrawler#19]
In the tapregion area of the code (somewhere close to tapregion.x) the game will crash at the start of the game with the following error:
`EXC_BAD_ACCESS (code=EXC_ARM_DA_ALIGN, address=0x70795477`

**Comment by lufinkey** [comment]
Not getting that on this end. it's probably a change you made.

**Comment by lufinkey** [comment]
I'm going to try to copy your load screen code, and see if I can get it working

**Comment by Kfeavel** [comment]
Alright. The error is weird though because even if I revert all of my changes it still occurs...

**Comment by lufinkey** [comment]
Try getting a copy of my current repo and trying it

**Comment by Kfeavel** [comment]
Still happening with most recent commit. Fresh copy of your repo.

**Comment by lufinkey** [comment]
I'll check in in xcode

**Comment by lufinkey** [comment]
Cleaning the project and re-running it fixes the issue

**Comment by lufinkey** [comment]
Wait actually found the actual bug. Fixed.
