### ISSUE TITLE
Occasional 'Graphical Leak' on Right Side of Screen

### ISSUE THREAD

**Issue by Kfeavel** [lufinkey/MobileBrawler#3]
Every now and then a white line appears on the far right side of the screen.

**Comment by lufinkey** [comment]
is this in the newer version? I haven't experienced this. Also please be more specific about what platform you're running it on.

**Comment by Kfeavel** [comment]
Looking into it. I'm running on an iPhone 5 (iOS 8.2 Beta).

**Comment by lufinkey** [comment]
simulator or device? and also, if you could provide a few screenshots, that'd be awesome.

**Comment by Kfeavel** [comment]
Device. I'll see if it comes up again. It is fairly rare. I've only seen it twice so far.

**Comment by Kfeavel** [comment]
I'm going to go ahead and close this. I'm unable to reproduce it.

**Comment by Kfeavel** [comment]
Got a screenshot!
![ios simulator screen shot jan 30 2015 10 04 39 pm](https://cloud.githubusercontent.com/assets/3119047/5986585/3aa08e9a-a8cc-11e4-99b9-3687e3c1074e.png)

**Comment by lufinkey** [comment]
How do I duplicate this?

**Comment by Kfeavel** [comment]
It should just be there. It is always visible for me. (Running in iOS Simulator right now by the way.)

**Comment by lufinkey** [comment]
Doesn't show on windows. I'll try it out tomorrow

**Comment by lufinkey** [comment]
what simulator is this (What is the screen size?)

**Comment by Kfeavel** [comment]
iPhone 5, Non-resizable, iOS 8.1 (Maybe 8.2?)

**Comment by lufinkey** [comment]
I can't seem to duplicate this on the latest version at all.

**Comment by Kfeavel** [comment]
If I remember correctly, it appears when transitioning from the main menu back to the title screen. (After fading to black.)

**Comment by lufinkey** [comment]
Alright I'll check it when I'm free again.
