### ISSUE TITLE
Potential Issue: Character's Info.plist Files

### ISSUE THREAD

**Issue by Kfeavel** [lufinkey/MobileBrawler#4]
Generally speaking, Xcode likes to only have one Info.plist file per project, which is used for application settings such as default orientation, version numbers, build numbers, compatible devices, etc. I would recommend changing the file names for the characters' plists from "Info.plist" to something like "character.plist"

**Comment by lufinkey** [comment]
Good call. I'll do that in the next commit.

**Comment by lufinkey** [comment]
Actually, I'm debating this, because of the nature of how characters are modules.

**Comment by Kfeavel** [comment]
Issue has been resolved in one of the more recent merges.
