### ISSUE TITLE
Character & Stage Module Structure

### ISSUE THREAD

**Issue by Kfeavel** [lufinkey/MobileBrawler#8]
At some point in the near future, I think it would be helpful to create plists to track all of the character's / stage's animations and assets. This way all characters / stages would be uniform and have the same file names. (Plist might not be necessary, just a uniform file naming system)

**Comment by lufinkey** [comment]
I wholeheartedly agree. I was actually heading in that direction

**Comment by lufinkey** [comment]
I was planning on using chaiscript for atleast part of the characters/stages

**Comment by Kfeavel** [comment]
@lufinkey I am unfamiliar with chaiscript so I may be slow in picking that part up if we go that direction.

**Comment by lufinkey** [comment]
it's very similar to javascript. And it's really nice to integrate into c++
